---
name: pre-release

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-pre-release:
    name: Publish Pre Release
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    needs:
      - build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          title: "Development Build"
          files: |
            macos-packages/chdig-macos-x86_64.gz
            windows-packages/chdig-windows.exe.gz
            linux-packages/chdig
            linux-packages/*.deb
            linux-packages/*.rpm
            linux-packages/*.tar.*
