---
name: pre-release

on:
  push:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-pre-release:
    name: Publish Pre Release
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    needs:
    - build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          macos-packages-x86_64/*
          macos-packages-arm64/*
          windows-packages-x86_64/*
          linux-packages-amd64/*
          linux-packages-aarch64/*
