---
name: pull_request

on:
  pull_request:
    types:
    - synchronize
    - reopened
    - opened
    branches:
    - main
    paths-ignore:
    - '**.md'
    - 'Documentation/**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
