---
name: release

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish-release:
    name: Publish Release
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    needs:
    - build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          macos-packages-x86_64/chdig-macos-x86_64.gz
          macos-packages-arm64/chdig-macos-arm64.gz
          windows-packages/chdig-windows.exe.zip
          linux-packages/chdig
          linux-packages/*.deb
          linux-packages/*.rpm
          linux-packages/*.tar.*
